---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../../base/]
namespace: default
labels:
  - includeSelectors: true
    pairs:
      app: stock-tech-momentum
images:
  - name: stock-tech-momentum
    newName: stock-tech-momentum
    newTag: latest
patchesStrategicMerge: [null]
